### 필수 패키지 Numpy
- ndarray 객체 형태 즉, shape 변환
- ND <---> 1D
    * view ndarray 변환 : obj.reshape() 메서드
    * copy ndarray 변환 : np.resize() 함수

- ND ---> 1D
    * view ndarray 변환 : obj.ravel() 메서드
    * copy ndarray 변환 : obj.flatten() 함수

- view ndarray란?
    * 데이터는 동일하게, 형태만 다르게 표현

- copy ndarray란?
    * 데이터를 새롭게 저장한 새로운 ndarray

In [60]:
#모듈 로딩
import numpy as np

print(np.__version__) #파이썬 _ _xxx_ _, _ _ xxx_ _() -> 매직 변수/함수

1.26.4


- 1D --> ND 또는 ND --> 1D 변환

In [61]:
### reshpae()
arr1 = np.ones((2,5), dtype=np.int8)
arr1, arr1.ndim

(array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=int8),
 2)

In [62]:
### 2D (2,5) --> 1D (10,)
arr2 = arr1.reshape((10,))
print(arr1, arr2, sep='\n')

[[1 1 1 1 1]
 [1 1 1 1 1]]
[1 1 1 1 1 1 1 1 1 1]


In [63]:
### 1D (10,) --> 1D (1,10) (5,2) (2,5) (10,1)
arr3 = arr2.reshape((5,2))
arr3

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

### 행과 영 중에 하나만 지정하고 나머지는 계산해서 설정 -> -1

In [64]:
arr4 = arr2.reshape((-1,2))
print(arr4)

print('-----------------------')

arr5 = arr2.reshape((2, -1))
print(arr5)

print('-----------------------')

arr6 = arr2.reshape((1, 2, -1))
print(arr5)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
-----------------------
[[1 1 1 1 1]
 [1 1 1 1 1]]
-----------------------
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [65]:
#배열의 원소값 변경 : 배열변수명[인덱스] = 새로운 값
arr2[0]=100
arr2

array([100,   1,   1,   1,   1,   1,   1,   1,   1,   1], dtype=int8)

In [66]:
### -> reshape() 메서드 : view ndarray
### 새로운 ndarray 생성하지 않고, 표현 형식만 변형
### 원소 데이터 변경 시 모두 변경됨
print(arr1, arr2, sep='\n')

[[100   1   1   1   1]
 [  1   1   1   1   1]]
[100   1   1   1   1   1   1   1   1   1]


In [70]:
### resize() : 복사본을 생성한 새로운 ndarray 객체 반환
### [주의] resize() 메서드일 졍우는 view ndarray 반환
arr9 = np.array([[11,22,33], [44,55,66]])
arr7 = np.resize(arr9, (6,1))

print(arr9, arr7, sep='\n')

[[11 22 33]
 [44 55 66]]
[[11]
 [22]
 [33]
 [44]
 [55]
 [66]]


- ND --> 1D 형태 변환

In [68]:
### -> view nadrray 반환 ravel()
a3 = arr9.ravel()
print(a3)

arr9[0] = 9
print(arr9, a3, sep='\n')

[11 22 33 44 55 66]
[[ 9]
 [22]
 [33]
 [44]
 [55]
 [66]]
[ 9 22 33 44 55 66]


In [69]:
### -> copy ndarry 반환 flatten()
a3 = arr9.flatten()
print(a3)

arr9[0] = 9
print(arr9, a3, sep='\n')

[ 9 22 33 44 55 66]
[[ 9]
 [22]
 [33]
 [44]
 [55]
 [66]]
[ 9 22 33 44 55 66]
