### 필수 패키지 Numpy 이해
- 배열 형식의 데이터 저장 -> ndarray 객체
- 조건 : 동일 데이터 타입을 연속된 메모리 공간에 저장

In [1]:
#모듈 로딩
import numpy as np

import my_func as mf

In [2]:
#ndarray 객체/인스턴스 생성 - 방법[1] np.array()

arr1 = np.array(10) #주소 저장, 스칼라 Scalar

arr1

array(10)

In [3]:
#ndarray 객체/인스턴스 속성 확인/읽기

print(f'shape : {arr1.shape}')
print(f'ndim : {arr1.ndim}D')
print(f'size : {arr1.size}개')
print(f'itemsize : {arr1.itemsize}바이트')
print(f'dtype : {arr1.dtype}')
print(f'data : {arr1.data}') #주소값

shape : ()
ndim : 0D
size : 1개
itemsize : 4바이트
dtype : int32
data : <memory at 0x000001F96AE16CC0>


In [4]:
mf.printInfo(arr1, "myArr")

===========[myArr]==========
shape : ()
ndim : 0D
size : 1개
itemsize : 4바이트
dtype : int32
data : <memory at 0x000001F96AE16D60>
10


In [5]:
# 1차원 배열 즉, 벡터(Vector)

arr2 = np.array([11,22,33])
mf.printInfo(arr2, 'arr2')

===========[arr2]==========
shape : (3,)
ndim : 1D
size : 3개
itemsize : 4바이트
dtype : int32
data : <memory at 0x000001F96C1F3F40>
[11 22 33]


In [6]:
# 2차원 배열 즉, 행렬(Matrix)
arr3 = np.array([[11,22,33],[44,55,66]])
mf.printInfo(arr3, 'arr3')

===========[arr3]==========
shape : (2, 3)
ndim : 2D
size : 6개
itemsize : 4바이트
dtype : int32
data : <memory at 0x000001F96AD74A00>
[[11 22 33]
 [44 55 66]]


In [7]:
# 3차원 배열 즉, 다차원 배열
arr4 = np.array([[[11,22,33],[44,55,66]], [[11,22,33],[44,55,66]]])
mf.printInfo(arr4, 'arr4')

===========[arr4]==========
shape : (2, 2, 3)
ndim : 3D
size : 12개
itemsize : 4바이트
dtype : int32
data : <memory at 0x000001F96ACD9A90>
[[[11 22 33]
  [44 55 66]]

 [[11 22 33]
  [44 55 66]]]


In [8]:
# 3차원 배열 즉, 다차원 배열 / 데이터 타입 : 부호 없는 정수 1 바이트
arr5 = np.array([[[11,22,33],[44,55,66]], [[11,22,33],[44,55,66]]],
                dtype='uint8')
mf.printInfo(arr5, 'arr5')

===========[arr5]==========
shape : (2, 2, 3)
ndim : 3D
size : 12개
itemsize : 1바이트
dtype : uint8
data : <memory at 0x000001F96ACD9A90>
[[[11 22 33]
  [44 55 66]]

 [[11 22 33]
  [44 55 66]]]


In [9]:
# 1차원 배열 즉, 벡터(Vector) / 데이터 타입 : 실수

arr6 = np.array([11,22], dtype='float')
mf.printInfo(arr6, 'arr6')

===========[arr6]==========
shape : (2,)
ndim : 1D
size : 2개
itemsize : 8바이트
dtype : float64
data : <memory at 0x000001F96C1F3F40>
[11. 22.]


- ndarray 객체/인스턴스 생성 - 방법[2] 특정값으로 채운 배열

In [11]:
### np.ones() : 모든 값을 1으로 채운 배열 생성
arr2_1 = np.ones(3)
mf.printInfo(arr2_1, 'arr2_1')

arr2_1 = np.ones(3, dtype='int')
mf.printInfo(arr2_1, 'arr2_1')

===========[arr2_1]==========
shape : (3,)
ndim : 1D
size : 3개
itemsize : 8바이트
dtype : float64
data : <memory at 0x000001F96C2C8040>
[1. 1. 1.]
===========[arr2_1]==========
shape : (3,)
ndim : 1D
size : 3개
itemsize : 4바이트
dtype : int32
data : <memory at 0x000001F96C2C8040>
[1 1 1]


In [14]:
### np.zeros() : 모든 값을 0으로 채운 배열 생성
arr2_2 = np.zeros((3,2))
mf.printInfo(arr2_2, 'arr2_2')

arr2_2 = np.zeros((3,2,2), dtype='uint8')
mf.printInfo(arr2_2, 'arr2_2')

===========[arr2_2]==========
shape : (3, 2)
ndim : 2D
size : 6개
itemsize : 8바이트
dtype : float64
data : <memory at 0x000001F96C201BA0>
[[0. 0.]
 [0. 0.]
 [0. 0.]]
===========[arr2_2]==========
shape : (3, 2, 2)
ndim : 3D
size : 12개
itemsize : 1바이트
dtype : uint8
data : <memory at 0x000001F96C297040>
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [19]:
### np.full() : 모든 값을 원하는 값으로 채운 배열 생성
arr2_2 = np.full((3,2), 5)
mf.printInfo(arr2_2, 'arr2_2')

arr2_2 = np.full((2,2,2,3), fill_value=7, dtype='uint8') #3차원이 두개 -> 4차원
mf.printInfo(arr2_2, 'arr2_2')

===========[arr2_2]==========
shape : (3, 2)
ndim : 2D
size : 6개
itemsize : 4바이트
dtype : int32
data : <memory at 0x000001F96C201BA0>
[[5 5]
 [5 5]
 [5 5]]
===========[arr2_2]==========
shape : (2, 2, 2, 3)
ndim : 4D
size : 24개
itemsize : 1바이트
dtype : uint8
data : <memory at 0x000001F96C2B1940>
[[[[7 7 7]
   [7 7 7]]

  [[7 7 7]
   [7 7 7]]]


 [[[7 7 7]
   [7 7 7]]

  [[7 7 7]
   [7 7 7]]]]


- ndarray 객체/인스턴스 생성 - 방법[3] 다른 array와 비슷한 객체 생성

In [24]:
arr3_0 = np.eye(5,5)
arr3_0

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
### 기존 array와 동일한 shape의 array 생성 -> ones_like()
arr3_1 = np.array([[11,22,33], [44,55,66]])
arr3_1

array([[11, 22, 33],
       [44, 55, 66]])

In [21]:
arr3_2 = np.ones_like(arr3_1)
arr3_2

array([[1, 1, 1],
       [1, 1, 1]])

In [25]:
arr3_3 = np.zeros_like(arr3_1)
arr3_3

array([[0, 0, 0],
       [0, 0, 0]])

In [26]:
arr3_4 = np.full_like(arr3_1, 9)
arr3_4

array([[9, 9, 9],
       [9, 9, 9]])

- ndarray 객체/인스턴스 생성 - 방법[4] 데이터 범위 지정으로 생성

In [27]:
# np.arnage(시작, 종료+1, 간격) 시작 <= ~ <종료
arr4_1 = np.arange(5)
arr4_1

array([0, 1, 2, 3, 4])

In [28]:
arr4_2 = np.arange(1,5)
arr4_2

array([1, 2, 3, 4])

In [31]:
arr4_3 = np.arange(2, 11, 2, dtype=np.float32)
arr4_3

array([ 2.,  4.,  6.,  8., 10.], dtype=float32)

In [34]:
arr4_4 = np.arange(1, 6, step=0.5, dtype=np.float32)
arr4_5 = np.arange(1.0, 6.0, step=0.5, dtype=np.int32)
print(arr4_4, arr4_5)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5] [1 1 1 1 1 1 1 1 1 1]


In [37]:
# linspace(start, stop, num=50, endpoint=True) 시작 <= ~ <= 종료
arr4_6 = np.linspace(1,50, num=15)
arr4_6

array([ 1. ,  4.5,  8. , 11.5, 15. , 18.5, 22. , 25.5, 29. , 32.5, 36. ,
       39.5, 43. , 46.5, 50. ])

In [39]:
arr4_7 = np.linspace(1,50, num=15, endpoint=False, retstep=True)
arr4_7

(array([ 1.        ,  4.26666667,  7.53333333, 10.8       , 14.06666667,
        17.33333333, 20.6       , 23.86666667, 27.13333333, 30.4       ,
        33.66666667, 36.93333333, 40.2       , 43.46666667, 46.73333333]),
 3.2666666666666666)