### 필수 패키지 Numpy - 집계함수

In [1]:
import numpy as np

In [3]:
# ndarray 데이터 생성
d1 = np.arange(1, 11)
d2 = np.resize(d1, (2,5))

print(d1, d2, sep='\n')

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
print(d1.shape, d2.shape, sep='\n')

(10,)
(2, 5)


In [5]:
d1[0] = 8

print(d1, d2, sep='\n')

[ 8  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


- 1D 배열의 집계함수

In [11]:
print(f'd1.sum() -> {d1.sum()}')
print(f'd1.mean() -> {d1.mean()}')
print(f'd1.min() -> {d1.min()}, {d1.argmin()} 원소/요소')
print(f'd1.max() -> {d1.max()}, {d1.argmax() }원소/요소')
print(f'd1.sort() -> {d1.sort()}, {d1.argsort() }원소/요소')

d1.sum() -> 62
d1.mean() -> 6.2
d1.min() -> 2, 1 원소/요소
d1.max() -> 10, 9원소/요소
d1.sort() -> None, [0 1 2 3 4 5 6 7 8 9]원소/요소


- 2D 배열의 집계함수

In [12]:
### 대상 : 전체 요소/원소
print(f'd2.sum() -> {d2.sum()}')
print(f'd2.mean() -> {d2.mean()}')
print(f'd2.min() -> {d2.min()}, {d2.argmin()} 원소/요소')
print(f'd2.max() -> {d2.max()}, {d2.argmax() }원소/요소')

d2.sum() -> 55
d2.mean() -> 5.5
d2.min() -> 1, 0 원소/요소
d2.max() -> 10, 9원소/요소
d2.sort() -> None, [[0 1 2 3 4]
 [0 1 2 3 4]]원소/요소


In [18]:
### 대상 : 행 방향 기준 요소/원소 : 모든 컬럼을 사용해서 한개 행
print(d2)

print(f'd2.sum() -> {d2.sum(axis=1)}') #행 전체
print(f'd2.mean() -> {d2.mean(axis=1)}')
print(f'd2.min() -> {d2.min(axis=1)}, {d2.argmin(axis=1)} 원소/요소')
print(f'd2.max() -> {d2.max(axis=1)}, {d2.argmax(axis=1) }원소/요소')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
d2.sum() -> [15 40]
d2.mean() -> [3. 8.]
d2.min() -> [1 6], [0 0] 원소/요소
d2.max() -> [ 5 10], [4 4]원소/요소


In [17]:
### 대상 : 행 방향 기준 요소/원소 : 모든 컬럼을 사용해서 한개 행
print(d2)

print(f'd2.sum() -> {d2.sum(axis=0)}') #위 아래
print(f'd2.mean() -> {d2.mean(axis=0)}')
print(f'd2.min() -> {d2.min(axis=0)}, {d2.argmin(axis=0)} 원소/요소')
print(f'd2.max() -> {d2.max(axis=0)}, {d2.argmax(axis=0) }원소/요소')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
d2.sum() -> [ 7  9 11 13 15]
d2.mean() -> [3.5 4.5 5.5 6.5 7.5]
d2.min() -> [1 2 3 4 5], [0 0 0 0 0] 원소/요소
d2.max() -> [ 6  7  8  9 10], [1 1 1 1 1]원소/요소
