### 필수 패키지 Numpy - 축 (axis) 변경

In [1]:
import numpy as np

In [2]:
nparray01=np.array( [ [1,2,3,4,5], [6,7, 8, 9, 10] ])

### T 속성 : 행 <--> 열 축 변경
print('nparray01.shape =', nparray01.shape)
print(nparray01)
nparray01=nparray01.T
print('nparray01.shape =', nparray01.shape)
print(nparray01)

nparray01.shape = (2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
nparray01.shape = (5, 2)
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


### 2차원 배열 축 변경

In [4]:

### swapaxes() 메서드 : 2개 축 변경

data = np.array([[1, 2, 3], 
                [4, 5, 6],
                [4, 5, 6],
                [4, 5, 6]])

# 축 0(행)과 축 1(열)을 교환
swapped_arr = np.swapaxes(data, 0, 1)

print(swapped_arr)

[[1 4]
 [2 5]
 [3 6]]


In [12]:
# 2차원 배열 생성
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# T 속성을 사용하여 배열 전치
transposed_arr = arr.T

print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


### 3차원 배열 축 변경

In [14]:
data2 = np.array([[[1, 2], 
                 [3, 4]], 
                [[5, 6], 
                 [7, 8]]])

# 축 0과 축 2를 교환
swapped_arr = np.swapaxes(data2, 0, 2)
swapped_arr1 = data2.swapaxes(0,2)

print(swapped_arr, swapped_arr1, sep='\n')


[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]
[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]


In [16]:
# 3차원 배열 생성
arr = np.array([[[1, 2, 3], 
                 [3, 4, 5]], 
                [[5, 6, 7], 
                 [7, 8, 9]]])

# T 속성을 사용하여 배열 전치
transposed_arr = arr.T

print(transposed_arr)

[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]

 [[3 7]
  [5 9]]]


In [18]:
###trnaspose : 3 축 변경 -> 축 순서 설정

print(arr.shape)

arr = arr.transpose(1, 2, 0)
print(arr.shape)

(2, 2, 3)
(2, 3, 2)
