### 텐서(Tensor) 이해
- DL 프레임워크 Tensorflow에서 데이터를 저장하는 타입
- N차원 배열
- 일반적인 파이썬 문법 변수 선언 X -> Tensor 생성 해야 하기 때문에

In [1]:
##모듈 로딩
import tensorflow as tf

- [상수 데이터 저장 텐서] --> tf.constant()

In [2]:
# 스칼라
data1 = tf.constant(8)

print(type(data1), data1, sep='\n')

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(8, shape=(), dtype=int32)


In [4]:
# 벡터 1D
data2 = tf.constant([8])

print(type(data2), data2, sep='\n')

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor([8], shape=(1,), dtype=int32)


In [7]:
# 벡터 2D
data3 = tf.constant([[8]])

print(type(data3), data3, sep='\n')
print(f'텐서 속성\n-> shape{data3.shape}')
print(f'ndim\n-> ndim{data3.ndim}D')
print(f'dtype\n-> dtype{data3.dtype}')

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor([[8]], shape=(1, 1), dtype=int32)
텐서 속성
-> shape(1, 1)
ndim
-> ndim2D
dtype
-> dtype<dtype: 'int32'>


In [15]:
data1 = tf.constant(['apple', 'kiwi'])

print(type(data1), data1, sep='\n')

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor([b'apple' b'kiwi'], shape=(2,), dtype=string)


- [변수 데이터 저장 텐서] -> tf.Variable() 객체

In [8]:
# 0D 스칼라
data2_1 = tf.Variable(10)

print(type(data2_1), data2_1, sep='\n')

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>


In [10]:
# 1D Vector
data2_2 = tf.Variable([10])

print(type(data2_2), data2_2, sep='\n')
print(data2_2.shape, data2_2.name)

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([10])>
(1,) Variable:0


In [12]:
# 2D Matrix
data2_3 = tf.Variable([['apple', 'kiwi']])

print(type(data2_3), data2_3, sep='\n')
print(data2_3.shape, data2_3.name)

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'Variable:0' shape=(1, 2) dtype=string, numpy=array([[b'apple', b'kiwi']], dtype=object)>
(1, 2) Variable:0
