#### 다중분류 모델
- 손실 함수
- 성능평가

- [1] 모듈 로딩 및 데이터 준비 <hr>

In [5]:
# 모듈 로딩
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.data import Dataset

import numpy as np
import matplotlib.pyplot as plt


In [6]:
### 데이터 로딩 -> 내장 데이터셋 load_data()

(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [7]:
print(f'X_train : {X_train.shape}, y_train : {y_train.shape}')
print(f'X_test : {X_test.shape}, y_test : {y_test.shape}')

X_train : (60000, 28, 28), y_train : (60000,)
X_test : (10000, 28, 28), y_test : (10000,)


- [2] 데이터 전처리 <hr>
    * 피쳐 : 타입, 정규화, 1D
    * 타겟 : 인코딩 -> One-Hot Encoding

In [8]:
## 피쳐 -> 타입, 정규화 (0.0 ~ 1.0), 2D -> 1D
## [1] ) ~ 255 -> 0.0 ~ 1.0
X_train = X_train/255
X_test = X_test/255

print(f'x_train_max : {X_train.max()} , x_train_min : {X_train.min()}, x_train_shape : {X_train.shape}, x_train_dtype : {X_train.dtype}')
print(f'x_test_max : {X_test.max()} , x_test_min : {X_test.min()}, x_test_shape : {X_test.shape}, x_test_dtype : {X_test.dtype}')

x_train_max : 1.0 , x_train_min : 0.0, x_train_shape : (60000, 28, 28), x_train_dtype : float64
x_test_max : 1.0 , x_test_min : 0.0, x_test_shape : (10000, 28, 28), x_test_dtype : float64


In [9]:
## [2] float64 -> float 32
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

In [11]:
## [3] 2D (28, 28) -> 1D (28*28)
X_train, X_test = X_train.reshape([-1, 28*28]), X_test.reshape([-1, 28*28]) # -1 배열의 크기를 자동으로 계산

print(f'X_train shape : {X_train.shape}, x_test shape : {X_test.shape}')

X_train shape : (60000, 784), x_test shape : (10000, 784)


In [12]:
## 라벨 ->  One-Hot Encoding
y_train = tf.one_hot(y_train, depth=10)
y_test = tf.one_hot(y_test, depth=10)

print(y_train[:3])

tf.Tensor(
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]], shape=(3, 10), dtype=float32)
